configfile: "config/config.yaml"

include: "rules/diffab.smk"
include: "rules/visualization.smk"
include: "rules/ml.smk"

all_diff_files = expand(
    "results/{tool}/differentials.processed.tsv",
    tool=config["tools"]
)
all_diff_files.append("results/concatenated_differentials.tsv")

all_ml = expand(
    "results/{tool}/ml/regression/model_data.pctile_{pctile}.joblib",
    tool=config["tools"],
    pctile=config["log_ratio_feat_pcts"]
)

all_viz_files = expand(
    "figures/{tool}_differentials.pdf",
    tool=config["tools"]
)
all_viz_files.extend(expand(
    "figures/{viz}.pdf",
    viz=["spearman_heatmap"]
))
all_viz_files.extend(expand(
    "figures/upset/upset_pctile_{pctile}.{location}.pdf",
    pctile=config["log_ratio_feat_pcts"],
    location=["numerator", "denominator"]
))
all_viz_files.append("results/qadabra.html")


rule all:
    input:
        all_diff_files + all_viz_files + all_ml


rule all_differentials:
    input:
        all_diff_files


rule all_ml:
    input:
        all_ml


rule all_visualizations:
    input:
        all_viz_files
