configfile: "config/config.yaml"

include: "rules/diffab.smk"
include: "rules/visualization.smk"

rule all:
    input:
        expand("results/{tool}/differentials.processed.tsv", tool=config["tools"])
