table: "data/table.biom"
metadata: "data/metadata.tsv"
model:
    covariate: anemia
    target: anemic
    reference: normal
    confounders:
        - sex
        - collection_cutoff
tools:
    - deseq2
    - ancombc
    - songbird
    - aldex2
    - edger
songbird_params:
    epochs: 5000
    differential_prior: 1
log_ratio_feat_pcts:
    - 5
    - 10
    - 15
    - 20
ml_params:
    n_splits: 10
    n_repeats: 5
