name: "Main CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: qadabra
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}

      - name: Install Snakemake & Snakedeploy
        shell: bash -l {0}
        run: mamba install snakemake snakedeploy

      - name: Lint
        uses: snakemake/snakemake-github-action@v1.24.0
        shell: bash -l {0}
        with:
            directory: .
            snakefile: workflow/Snakefile
            args: "--lint"

      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.24.0
        shell: bash -l {0}
        with:
            directory: .
            snakefile: workflow/Snakefile
            args: "--use-conda -j 10 --conda-cleanup-pkgs cache"

      - name: Test report
        uses: snakemake/snakemake-github-action@v1.24.0
        shell: bash -l {0}
        with:
            directory: .
            snakefile: workflow/Snakefile
            args: "--report report.zip"
