# github.com/snakemake-workflows/dna-seq-varlociraptor/blob/master/.github/workflows/main.yml
name: "Main CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        stagein: "mamba install -y -n snakemake --channel conda-forge --channel bioconda"
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs:
      - Linting
    steps:
    - uses: actions/checkout@v2

    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"
        stagein: "conda config --get channel_priority --json"

    - name: Test report
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--report report.zip"
